"""
src/twin_crosscheck.py
======================
Comprehensive batch vs. live cross-check verification script for Milestone 5b.

STRUCTURAL PROXY NOTICE
-----------------------
All telemetry derives from IOT-temp.csv (generic IoT temperature sensor log),
NOT refrigerated-transport operations. All injected anomalies are synthetic
proxy constructs. Detectors carry no food-safety significance.
See docs/AD_LOG.md (D1–D26).

DESIGN DECISIONS IMPLEMENTED
-----------------------------
D21 & D26: Rigorous cross-checking of live streaming alarms against frozen batch
          evaluations from Milestones 2, 3, and 4b.
          - Baseline: evaluated on all 30 synthetic injections (whole-series threshold, D24).
          - Isolation Forest: evaluated on the 6 test-side injections (scientific comparison).
            Train-side live alarms reported as demo-only (D26).
          - LSTM: evaluated on the 6 test-side injections (scientific comparison).
            Train-side live alarms reported as demo-only (D26).
D23: Explicit verification of continuous-buffer coverage vs. first-29-test-rows blind spot.

OUTPUTS
-------
- data/processed/twin_crosscheck_report.csv
"""

from __future__ import annotations

import logging
import pathlib
import sys
from typing import Any

import numpy as np
import pandas as pd

sys.path.insert(0, str(pathlib.Path(__file__).parent))
from config import SEARCH_HORIZON_MINUTES

# ── Logging ────────────────────────────────────────────────────────────────────
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
logger = logging.getLogger(__name__)

# ── Paths ──────────────────────────────────────────────────────────────────────
REPO_ROOT     = pathlib.Path(__file__).resolve().parents[1]
PROCESSED_DIR = REPO_ROOT / "data" / "processed"

INJECTION_LOG_CSV = PROCESSED_DIR / "injection_log.csv"
STATUS_CSV        = PROCESSED_DIR / "injection_train_test_status.csv"
BASELINE_EVAL_CSV = PROCESSED_DIR / "injection_evaluation_baseline.csv"
IF_EVAL_CSV       = PROCESSED_DIR / "if_evaluation.csv"
LSTM_EVAL_CSV     = PROCESSED_DIR / "lstm_evaluation.csv"

CROSSCHECK_REPORT_CSV = PROCESSED_DIR / "twin_crosscheck_report.csv"


def load_live_alarms() -> dict[str, dict[str, pd.DataFrame]]:
    """Load all 6 live alarm CSV files generated by twin_monitors.py."""
    detectors = ["baseline", "if", "lstm"]
    series_list = ["out", "in"]
    alarms: dict[str, dict[str, pd.DataFrame]] = {d: {} for d in detectors}

    for det in detectors:
        for s in series_list:
            path = PROCESSED_DIR / f"twin_alarms_{det}_{s}.csv"
            if not path.exists():
                raise FileNotFoundError(f"Missing live alarms file: {path}. Run twin_monitors.py first!")
            df = pd.read_csv(path, parse_dates=["ts"])
            alarms[det][s.capitalize()] = df

    return alarms


def find_first_live_alarm(
    df_alarms: pd.DataFrame,
    onset_ts: pd.Timestamp,
    end_ts: pd.Timestamp,
) -> pd.Timestamp | None:
    """Find the earliest alarm timestamp within [onset_ts, end_ts + SEARCH_HORIZON_MINUTES]."""
    horizon_end = end_ts + pd.Timedelta(minutes=SEARCH_HORIZON_MINUTES)
    in_win = df_alarms[
        (df_alarms["ts"] >= onset_ts)
        & (df_alarms["ts"] <= horizon_end)
        & (df_alarms["alarm"] == True)
    ]
    if in_win.empty:
        return None
    return in_win.iloc[0]["ts"]


def run_crosscheck() -> pd.DataFrame:
    """Run cross-check across all 30 injections and all 3 detectors."""
    logger.info("=== Cold Chain EWS — Twin Cross-Check (Milestone 5b) ===")

    inj_log = pd.read_csv(INJECTION_LOG_CSV, parse_dates=["start_timestamp"])
    status_df = pd.read_csv(STATUS_CSV, parse_dates=["start_ts", "end_ts"])
    base_eval = pd.read_csv(BASELINE_EVAL_CSV, parse_dates=["baseline_alarm_timestamp"])
    if_eval = pd.read_csv(IF_EVAL_CSV, parse_dates=["alarm_timestamp_IF"])
    lstm_eval = pd.read_csv(LSTM_EVAL_CSV, parse_dates=["alarm_timestamp_LSTM"])

    live_alarms = load_live_alarms()

    # Merge injection metadata
    merged = inj_log.merge(
        status_df[["injection_id", "train_test_status", "start_ts", "end_ts"]],
        on="injection_id",
    )

    report_rows: list[dict[str, Any]] = []

    # Counters
    counts = {
        "baseline": {"tested": 0, "matched": 0, "mismatched": 0},
        "if": {"test_tested": 0, "test_matched": 0, "test_mismatched": 0, "train_demo": 0},
        "lstm": {"test_tested": 0, "test_matched": 0, "test_mismatched": 0, "train_demo": 0},
    }

    for _, row in merged.iterrows():
        inj_id = row["injection_id"]
        series = row["series"]
        inj_type = row["type"]
        status = row["train_test_status"]
        onset_ts = pd.Timestamp(row["start_ts"])
        end_ts = pd.Timestamp(row["end_ts"])

        # 1. Baseline Detector (All 30 injections)
        b_batch_row = base_eval[base_eval["injection_id"] == inj_id].iloc[0]
        b_batch_ts = b_batch_row["baseline_alarm_timestamp"] if pd.notna(b_batch_row["baseline_alarm_timestamp"]) else None
        b_live_ts = find_first_live_alarm(live_alarms["baseline"][series], onset_ts, end_ts)

        b_match = (b_live_ts == b_batch_ts)
        counts["baseline"]["tested"] += 1
        if b_match:
            counts["baseline"]["matched"] += 1
            b_notes = "Exact match with M2 baseline (whole-series threshold, D24)"
        else:
            counts["baseline"]["mismatched"] += 1
            b_notes = f"MISMATCH: live={b_live_ts}, batch={b_batch_ts}"

        report_rows.append({
            "injection_id": inj_id,
            "series": series,
            "type": inj_type,
            "train_test_status": status,
            "detector": "baseline",
            "live_alarm_timestamp": b_live_ts,
            "batch_alarm_timestamp": b_batch_ts,
            "match": b_match,
            "notes": b_notes,
        })

        # 2. Isolation Forest Detector
        if_live_ts = find_first_live_alarm(live_alarms["if"][series], onset_ts, end_ts)
        if status == "test":
            counts["if"]["test_tested"] += 1
            if_batch_row = if_eval[if_eval["injection_id"] == inj_id].iloc[0]
            if_batch_ts = if_batch_row["alarm_timestamp_IF"] if pd.notna(if_batch_row["alarm_timestamp_IF"]) else None
            if_match = (if_live_ts == if_batch_ts)
            if if_match:
                counts["if"]["test_matched"] += 1
                if if_live_ts is not None:
                    if_notes = "Exact match with M3 batch test evaluation"
                else:
                    if_notes = "Exact match (both null in bounded window)"
            else:
                counts["if"]["test_mismatched"] += 1
                if_notes = f"MISMATCH: live={if_live_ts}, batch={if_batch_ts}"

            report_rows.append({
                "injection_id": inj_id,
                "series": series,
                "type": inj_type,
                "train_test_status": status,
                "detector": "if",
                "live_alarm_timestamp": if_live_ts,
                "batch_alarm_timestamp": if_batch_ts,
                "match": if_match,
                "notes": if_notes,
            })
        else:
            counts["if"]["train_demo"] += 1
            report_rows.append({
                "injection_id": inj_id,
                "series": series,
                "type": inj_type,
                "train_test_status": status,
                "detector": "if",
                "live_alarm_timestamp": if_live_ts,
                "batch_alarm_timestamp": None,
                "match": "not_applicable",
                "notes": "Demo only — model had training exposure (D26); batch value not computed for train",
            })

        # 3. LSTM Detector
        lstm_live_ts = find_first_live_alarm(live_alarms["lstm"][series], onset_ts, end_ts)
        if status == "test":
            counts["lstm"]["test_tested"] += 1
            lstm_batch_row = lstm_eval[lstm_eval["injection_id"] == inj_id].iloc[0]
            lstm_batch_ts = lstm_batch_row["alarm_timestamp_LSTM"] if pd.notna(lstm_batch_row["alarm_timestamp_LSTM"]) else None
            lstm_match = (lstm_live_ts == lstm_batch_ts)
            if lstm_match:
                counts["lstm"]["test_matched"] += 1
                if lstm_live_ts is not None:
                    lstm_notes = "Exact match with M4b batch test evaluation; onset post-dates first 29 test rows (unaffected by D23)"
                else:
                    lstm_notes = "Exact match (never flagged in window; onset post-dates first 29 test rows)"
            else:
                counts["lstm"]["test_mismatched"] += 1
                lstm_notes = f"MISMATCH: live={lstm_live_ts}, batch={lstm_batch_ts}"

            report_rows.append({
                "injection_id": inj_id,
                "series": series,
                "type": inj_type,
                "train_test_status": status,
                "detector": "lstm",
                "live_alarm_timestamp": lstm_live_ts,
                "batch_alarm_timestamp": lstm_batch_ts,
                "match": lstm_match,
                "notes": lstm_notes,
            })
        else:
            counts["lstm"]["train_demo"] += 1
            report_rows.append({
                "injection_id": inj_id,
                "series": series,
                "type": inj_type,
                "train_test_status": status,
                "detector": "lstm",
                "live_alarm_timestamp": lstm_live_ts,
                "batch_alarm_timestamp": None,
                "match": "not_applicable",
                "notes": "Demo only — model had training exposure (D26); batch value not computed for train",
            })

    report_df = pd.DataFrame(report_rows)
    report_df.to_csv(CROSSCHECK_REPORT_CSV, index=False)
    logger.info("Saved cross-check report to: %s (%d rows)", CROSSCHECK_REPORT_CSV.name, len(report_df))

    # Summary logging
    logger.info("=================================================================")
    logger.info("CROSS-CHECK VERIFICATION SUMMARY")
    logger.info("=================================================================")
    logger.info("Baseline: %d/30 matched (mismatched: %d)", counts["baseline"]["matched"], counts["baseline"]["mismatched"])
    logger.info("IF      : %d/6 test matched (mismatched: %d) | %d train demo rows",
                counts["if"]["test_matched"], counts["if"]["test_mismatched"], counts["if"]["train_demo"])
    logger.info("LSTM    : %d/6 test matched (mismatched: %d) | %d train demo rows",
                counts["lstm"]["test_matched"], counts["lstm"]["test_mismatched"], counts["lstm"]["train_demo"])

    # Detailed test-side display table
    test_report = report_df[report_df["train_test_status"] == "test"]
    logger.info("\nTEST-SIDE COMPARISON TABLE (Scientific Benchmark):\n%s",
                test_report[["injection_id", "detector", "live_alarm_timestamp", "batch_alarm_timestamp", "match"]].to_string(index=False))

    return report_df


if __name__ == "__main__":
    run_crosscheck()
